### ISSUE TITLE
Advertisements not handled by program

### ISSUE THREAD

**Issue by losbaltica** [PappaStalin/Spotify-Lyrics#10]
When commercials are running on the Spotify program getting following error

```
2019-04-04 18:48:00,393 - ERROR - Error occured
Traceback (most recent call last):
  File ".\__main__.py", line 140, in main
    spt.getsong()
  File ".\__main__.py", line 91, in getsong
    self.artist = json_data["item"]["artists"][0]["name"]
```

**Comment by TarmacDenter** [comment]
Looks like the logger is just sending you the ERROR. The `get_song()` should really be broken up. It resumes correctly when the song resumes, correct? It shouldn’t be crashing the program, just throwing the debug info out and moving on.

**Comment by losbaltica** [comment]
Yes, is just throwing an exception every 3 sec. When adds finish program just carrying on. Might be useful to send a single message like "Advertisement on waiting for next song etc."

**Comment by TarmacDenter** [comment]
@losbaltica this should fix your issue. It is a bandaid, for sure, but I'm going to start a larger refactoring and redesign of the `Spotify` class to fix some coupling issues that prevent adding services like Genius or other lyrics sources anyway. So it's the best I can do before then since those functions don't return anything that can be checked. They just change the inner state of that object. So without majorly changing the client code in `__main__.py` it'll have to do.
